apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.svcname }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.serviceport }}
      targetPort: {{ .Values.port }}
      nodePort: {{ .Values.nodePort }}
  selector:
    app: {{ .Values.container }}